export default function Head() {
    return (
      <>
        <title>Nstream AI Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </>
    );
  }
  